version: "3.9"
services:
  tileserver:
    build: ./tileserver
    container_name: map-tileserver
    init: true
    volumes:
      - ./tileserver:/data
    ports:
      - "8080:8080"
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: map-frontend
    init: true
    depends_on:
      - tileserver
    ports:
      - "8081:3000"
    restart: unless-stopped